version: '3'

services:
  rooms-service:
    container_name: rooms-service
    image: rooms-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
