version: '3'

services:
  rooms-service:
    container_name: rooms-service
    image: rooms-service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
